apiVersion: v1
kind: ConfigMap
metadata:
  name: carrental-config
data:
  application.properties: |
    spring.application.name=carrental
    spring.datasource.url=jdbc:mysql://mysql-service:3306/carrental
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    server.port=8081
