apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carrental-ingress
spec:
  rules:
  - host: carrental.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: carrental-service
            port:
              number: 8081
