apiVersion: v1
kind: Service
metadata:
  name: carrental-service
spec:
  selector:
    app: carrental
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer  # Or ClusterIP if using Ingress
